Tweak CI tag logging verbosity

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -104,15 +104,19 @@ jobs:
       - name: Check the package version has corresponding Git tag
         id: tagged
         shell: bash
-        run: git show-ref --tags --verify --quiet -- "refs/tags/${{ env.PROJECT_VERSION }}" && echo "tagExists=1" >> $GITHUB_OUTPUT || echo "tagExists=0" >> $GITHUB_OUTPUT
+        run: |
+          git show-ref --tags --verify --quiet -- "refs/tags/${{ env.PROJECT_VERSION }}" && echo "tagExists=1" >> $GITHUB_OUTPUT || echo "tagExists=0" >> $GITHUB_OUTPUT
+          git show-ref --tags --verify --quiet -- "refs/tags/${{ env.PROJECT_VERSION }}" && echo "Tag for current version exists" || echo "Tag for current version does not exist"
       # If the tag could not be fetched, show a message and abort the job.
-      - name: If tag version has a problem
+      - name: Abort if tag exists, or existence check fails
         if: steps.tagged.outputs.tagExists
         run: |
-          echo "The tag version has a problem."
+          echo "Output of 'tagged' step: ${{ steps.tagged.outputs.tagExists }}"
+          echo "Failed to check if tag exists."
           echo "PROJECT_VERSION: ${{ env.PROJECT_VERSION }}"
           echo "Tags $(git tag | wc -l):"
           git tag
+          git show-ref --tags --verify -- "refs/tags/${{ env.PROJECT_VERSION }}"
           exit 1
       # Run build to generate the release artifacts.
       # Tag does not exist AND trigger was manual. Deploy release artifacts!
